version: '3.4'

services:

  catalog-api-read:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://0.0.0.0:5136
      - ASPNETCORE_HTTP_PORTS=5136
    depends_on:
        - catalog-database
        - catalog-redis-cache
        - rabbitmq-container
    image: catalog-api-read
    container_name: catalog-api-read
    ports:
      - "5136:5136"
      - "5137:5137"

  catalog-api-write:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://0.0.0.0:5140
      - ASPNETCORE_HTTP_PORTS=5140
    depends_on:
        - catalog-database
        - catalog-redis-cache
        - rabbitmq-container
    image: catalog-api-write
    container_name: catalog-api-write
    ports:
      - "5140:5140"
      - "5141:5141"

  catalog-database:
    image: postgres:latest
    container_name: catalog-database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=CatalogContext
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pwd
    volumes:
      - ./.containers/catalog-db:/var/lib/postgressql/data

  catalog-redis-cache:
    image: redis:7.2.4-alpine
    command: "redis-server"
    ports:
      - "6371:6379"
    restart: always

  rabbitmq-container:
    image: rabbitmq:3.13-management-alpine
    container_name: 'rabbitmq-container'
    hostname: rabbitmq-container
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
        - "5672:5672"
        - "15672:15672"

  identity-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://0.0.0.0:5261
      - ASPNETCORE_HTTP_PORTS=5261
    depends_on:
        - identity-database
    image: identity-api
    container_name: identity-api
    ports:
      - "5261:5261"
      - "5262:5262"

  identity-database:
    image: postgres:latest
    container_name: identity-database
    ports:
      - "5433:5433"
    environment:
      - POSTGRES_DB=UserContext
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pwd
    volumes:
      - ./.containers/user-db:/var/lib/postgressql/data
    command: -p 5433

  gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://0.0.0.0:5003
      - ASPNETCORE_HTTP_PORTS=5003
    image: gateway
    container_name: gateway
    ports:
      - "5003:5003"

  cart-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://0.0.0.0:5264
      - ASPNETCORE_HTTP_PORTS=5264
    depends_on:
        - cart-database
    image: cart-api
    container_name: cart-api
    ports:
      - "5264:5264"
      - "5265:5265"

  cart-database:
    image: postgres:latest
    container_name: cart-database
    ports:
      - "5434:5434"
    environment:
      - POSTGRES_DB=CartContext
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pwd
    volumes:
      - ./.containers/cart-db:/var/lib/postgressql/data
    command: -p 5434
