version: '3.4'

services:

  catalog-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://0.0.0.0:5136
      - ASPNETCORE_HTTP_PORTS=5136
    image: catalog.api
    container_name: catalog-api
    ports:
      - "5136:5136"
      - "5137:5137"

  catalog-database:
    image: postgres:latest
    container_name: catalog-database
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=CatalogContext
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pwd
    volumes:
      - ./.containers/catalog-db:/var/lib/postgressql/data

  rabbitmq-container:
    image: rabbitmq:3.13-management-alpine
    container_name: 'rabbitmq-container'
    hostname: rabbitmq-container
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
        - '5672:5672'
        - '15672:15672'

  catalog-redis-cache:
    image: redis:7.2.4-alpine
    command: "redis-server"
    ports:
      - 6371:6379
    restart: always


    